#!/usr/bin/env bash
# ui-screenshots.sh — automatically capture per-tab screenshots of the ltc-gui UI.
#
# Generates a throwaway eframe example that runs the REAL app UI and cycles
# through all four tabs, captures one screenshot per tab, then removes the
# example again. Useful for keeping docs/README screenshots in sync as the
# UI evolves.
#
# Linux only (KDE Wayland, X11, or any wlroots compositor):
#   capture tool auto-detected: spectacle > import (ImageMagick, X11) > grim
#   override with: LTC_SHOT_CMD='my-tool -o {file}'   ({file} substituted)
#
# Usage:
#   scripts/ui-screenshots.sh                      # all tabs → assets/
#   scripts/ui-screenshots.sh --out /tmp/shots     # different output dir
#   scripts/ui-screenshots.sh --tabs clapper,offload
#   scripts/ui-screenshots.sh --width 1280 --height 900 --dwell 4
#   scripts/ui-screenshots.sh --text-scale 150 --suffix -150pct
#
# Output naming: <out>/ltc-timecode-generator-<tab><suffix>.png

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_DIR="$REPO_ROOT/assets"
TABS=(clapper settings converter offload)
WIDTH=1000
HEIGHT=800
DWELL=3      # seconds per tab inside the app
SETTLE=1.2   # seconds after a tab switch before capturing (let a frame draw)
TEXT_SCALE=100  # accessibility text scale in percent (50..400)
SUFFIX=""    # output filename suffix, e.g. "-150pct"
EXAMPLE="ltc-gui/examples/ui_screenshots.rs"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --out)   OUT_DIR="$2"; shift 2 ;;
        --tabs)  IFS=',' read -r -a TABS <<< "$2"; shift 2 ;;
        --width) WIDTH="$2"; shift 2 ;;
        --height) HEIGHT="$2"; shift 2 ;;
        --dwell) DWELL="$2"; shift 2 ;;
        --text-scale) TEXT_SCALE="$2"; shift 2 ;;
        --suffix) SUFFIX="$2"; shift 2 ;;
        -h|--help) sed -n '2,24p' "${BASH_SOURCE[0]}"; exit 0 ;;
        *) echo "unknown option: $1" >&2; exit 1 ;;
    esac
done

mkdir -p "$OUT_DIR"

# ── capture tool detection ────────────────────────────────────────────────
capture_shot() { # $1 = destination file
    local file="$1"
    if [[ -n "${LTC_SHOT_CMD:-}" ]]; then
        ${LTC_SHOT_CMD/\{file\}/"$file"}
    elif command -v spectacle >/dev/null 2>&1; then
        spectacle -b -n -f -o "$file" >/dev/null 2>&1
    elif command -v import >/dev/null 2>&1; then
        import -window root "$file"
    elif command -v grim >/dev/null 2>&1; then
        grim "$file"
    else
        echo "error: no capture tool found (spectacle/import/grim)" >&2
        exit 1
    fi
}

# ── throwaway example: real app UI + automatic tab cycling ───────────────
mkdir -p "$(dirname "$REPO_ROOT/$EXAMPLE")"
cat > "$REPO_ROOT/$EXAMPLE" <<'EOF'
//! Throwaway harness generated by scripts/ui-screenshots.sh — NOT committed.
//! Runs the real app UI and cycles through the tabs, printing a
//! `SNAPSHOT-TAB <name>` line each time a tab becomes active.

#[path = "../src/app.rs"]
mod app;
#[path = "../src/clap_anim.rs"]
mod clap_anim;
#[path = "../src/ids.rs"]
mod ids;
#[path = "../src/shadows.rs"]
mod shadows;
#[path = "../src/text.rs"]
mod text;
#[path = "../src/theme.rs"]
mod theme;
#[path = "../src/widgets/mod.rs"]
mod widgets;

use app::{AppState, Tab};
use std::collections::HashSet;
use std::time::{Duration, Instant};

fn tab_name(tab: Tab) -> &'static str {
    match tab {
        Tab::Clapper => "clapper",
        Tab::Settings => "settings",
        Tab::Converter => "converter",
        Tab::Offload => "offload",
    }
}

fn next_tab(tab: Tab) -> Tab {
    match tab {
        Tab::Clapper => Tab::Settings,
        Tab::Settings => Tab::Converter,
        Tab::Converter => Tab::Offload,
        Tab::Offload => Tab::Clapper,
    }
}

struct CycleApp {
    inner: AppState,
    switched_at: Instant,
    dwell: Duration,
    announced: bool,
    /// Snapshot text-scale override (LTC_SNAPSHOT_TEXT_SCALE), re-applied
    /// after AppState::logic each frame.
    scale_override: Option<u32>,
    /// Tabs the driver wants (LTC_SNAPSHOT_TABS); the app exits once each
    /// has been shown for one full dwell.
    wanted: HashSet<String>,
    shown: HashSet<String>,
    all_shown: bool,
}

impl CycleApp {
    fn announce(&mut self) {
        self.announced = true;
        let name = tab_name(self.inner.active_tab).to_string();
        if self.wanted.contains(&name) && self.shown.insert(name) {
            self.all_shown = self.shown.len() == self.wanted.len();
        }
        println!("SNAPSHOT-TAB {}", tab_name(self.inner.active_tab));
        use std::io::Write;
        std::io::stdout().flush().ok();
    }

    fn switch(&mut self) {
        if self.all_shown {
            println!("SNAPSHOT-DONE");
            use std::io::Write;
            std::io::stdout().flush().ok();
            std::process::exit(0);
        }
        self.inner.active_tab = next_tab(self.inner.active_tab);
        self.switched_at = Instant::now();
        self.announce();
    }
}

impl eframe::App for CycleApp {
    fn logic(&mut self, ctx: &egui::Context, frame: &mut eframe::Frame) {
        if self.switched_at.elapsed() >= self.dwell {
            self.switch();
        }
        AppState::logic(&mut self.inner, ctx, frame);
        // The app re-applies the engine-owned scale every frame; pin the
        // snapshot override so captures can use a different scale.
        if let Some(percent) = self.scale_override {
            text::set_text_scale(percent);
        }
    }

    fn ui(&mut self, ui: &mut egui::Ui, frame: &mut eframe::Frame) {
        if !self.announced {
            // first frame drawn — window is mapped; report the initial tab
            // so the driver can capture it too
            self.announce();
        }
        AppState::ui(&mut self.inner, ui, frame);
    }
}

fn main() {
    let dwell = Duration::from_secs(
        std::env::var("LTC_SNAPSHOT_DWELL").ok().and_then(|v| v.parse().ok()).unwrap_or(3),
    );
    if let Ok(percent) = std::env::var("LTC_SNAPSHOT_TEXT_SCALE") {
        text::set_text_scale(percent.trim().parse().expect("bad LTC_SNAPSHOT_TEXT_SCALE"));
    }
    let wanted: HashSet<String> = std::env::var("LTC_SNAPSHOT_TABS")
        .unwrap_or_else(|_| "clapper,settings,converter,offload".into())
        .split(',')
        .map(str::trim)
        .filter(|s| !s.is_empty())
        .map(str::to_string)
        .collect();
    let size = std::env::var("LTC_SNAPSHOT_SIZE").unwrap_or_else(|_| "1000x800".into());
    let mut dims = size.split('x');
    let width: f32 = dims.next().and_then(|v| v.parse().ok()).unwrap_or(1000.0);
    let height: f32 = dims.next().and_then(|v| v.parse().ok()).unwrap_or(800.0);
    let cli = gui_engine::cli::parse_args();
    match gui_engine::cli::process_cli(cli) {
        gui_engine::cli::CliOutcome::Done => {}
        gui_engine::cli::CliOutcome::RunGui { cmd_tx, state, event_rx } => {
            let log_buffer = gui_engine::log_buffer::init_logger(
                gui_engine::log_buffer::DEFAULT_LOG_FILTER,
            )
            .expect("Failed to initialize logger");
            let app = CycleApp {
                inner: AppState::new(cmd_tx, event_rx, state, log_buffer),
                switched_at: Instant::now(),
                dwell,
                announced: false,
                scale_override: std::env::var("LTC_SNAPSHOT_TEXT_SCALE")
                    .ok()
                    .map(|p| p.trim().parse().expect("bad LTC_SNAPSHOT_TEXT_SCALE")),
                wanted,
                shown: HashSet::new(),
                all_shown: false,
            };
            let options = eframe::NativeOptions {
                viewport: egui::ViewportBuilder::default()
                    .with_inner_size([width, height])
                    .with_title("LTC Timecode Generator"),
                glow_options: eframe::egui_glow::GlowConfiguration {
                    vsync: false,
                    ..Default::default()
                },
                ..Default::default()
            };
            eframe::run_native(
                "LTC Timecode Generator",
                options,
                Box::new(move |cc| {
                    theme::install_fonts(&cc.egui_ctx);
                    Ok(Box::new(app))
                }),
            )
            .expect("eframe error");
        }
    }
}
EOF

trap 'rm -f "$REPO_ROOT/$EXAMPLE"; rmdir "$(dirname "$REPO_ROOT/$EXAMPLE")" 2>/dev/null || true; [[ -n "${APP_PID:-}" ]] && kill "$APP_PID" 2>/dev/null || true' EXIT

echo ">> building screenshot harness ..."
(cd "$REPO_ROOT" && cargo build -p ltc-gui --example ui_screenshots >/dev/null)

LOG="$(mktemp)"
echo ">> running app (dwell ${DWELL}s/tab, text-scale ${TEXT_SCALE}%), capturing to $OUT_DIR"
LIBGL_ALWAYS_SOFTWARE=1 LTC_SNAPSHOT_DWELL="$DWELL" LTC_SNAPSHOT_SIZE="${WIDTH}x${HEIGHT}" \
    LTC_SNAPSHOT_TEXT_SCALE="$TEXT_SCALE" \
    LTC_SNAPSHOT_TABS="$(IFS=,; echo "${TABS[*]}")" \
    "$REPO_ROOT/target/debug/examples/ui_screenshots" > "$LOG" 2>&1 &
APP_PID=$!

# Drive captures off the app's SNAPSHOT-TAB lines, tab-filtered to --tabs.
wanted=" $(printf '%s ' "${TABS[@]}") "
captured=()
line_no=0
# safety net only — the app exits itself after one full pass (SNAPSHOT-DONE)
deadline=$(( SECONDS + DWELL * (${#TABS[@]} + 2) + 30 ))
while [[ $SECONDS -lt $deadline ]]; do
    # read only newly-appeared lines
    total=$(wc -l < "$LOG" 2>/dev/null || echo 0)
    while [[ $line_no -lt $total ]]; do
        line=$(sed -n "$((line_no + 1))p" "$LOG")
        line_no=$((line_no + 1))
        case "$line" in
            SNAPSHOT-TAB\ *)
                tab="${line#SNAPSHOT-TAB }"
                if [[ "$wanted" != *" $tab "* ]]; then continue; fi
                sleep "$SETTLE"
                dest="$OUT_DIR/ltc-timecode-generator-$tab${SUFFIX}-tab.png"
                if capture_shot "$dest" && [[ -s "$dest" ]]; then
                    captured+=("$tab")
                    echo "   captured $tab -> $dest"
                else
                    echo "   warning: capture for '$tab' produced no image" >&2
                fi
                ;;
            SNAPSHOT-DONE*) break 2 ;;
        esac
    done
    kill -0 "$APP_PID" 2>/dev/null || break
    sleep 0.2
done

kill "$APP_PID" 2>/dev/null || true
wait "$APP_PID" 2>/dev/null || true
rm -f "$LOG"

missing=()
for tab in "${TABS[@]}"; do
    found=no
    for c in "${captured[@]:-}"; do [[ "$c" == "$tab" ]] && found=yes; done
    [[ "$found" == no ]] && missing+=("$tab")
done
if [[ ${#missing[@]} -gt 0 ]]; then
    echo "error: no screenshot captured for: ${missing[*]}" >&2
    exit 1
fi
echo ">> done: ${#captured[@]} screenshot(s) in $OUT_DIR"
